### ISSUE TITLE
Parallel feature is not working

### ISSUE THREAD

**Issue by deadmoto** [opencredo/test-automation-quickstart#1]
I downloaded examples and modified steps to print current thread name to console.
When I launch tests using Maven I see output for one thread only.
I tried Java 6, 7 and 8 and Maven 3.0.x, 3.1.x, 3.2.x and 3.3.x.
Please check if your examples are still working.

**Comment by tristanmccarthy** [comment]
I've updated the versions and cleaned everything up a bit, can see parallel working fine when running mvn clean install -Pui-acceptance-tests. May have been a versioning issue with the surefire plugin.
